### ISSUE TITLE
ide警告

### ISSUE THREAD

**Issue by downdawn** [wu-clan/fastapi_sqlalchemy_mysql#3]
![image](https://user-images.githubusercontent.com/41266749/227494837-89a24923-f643-4415-b9ca-79f4caa61038.png)
请问有人出现这种警告吗？

**Comment by wu-clan** [comment]
没有遇到过，检查一下是否使用了新的独立虚拟环境，检查全局是否存在`sqlalchemy2-stubs`这个依赖包，有的话卸载了再看看

**Comment by downdawn** [comment]
感谢，确实是sqlalchemy2-stubs的问题

**Comment by wu-clan** [comment]
我想它可以关闭了
