### ISSUE TITLE
APScheduler示例

### ISSUE THREAD

**Issue by downdawn** [wu-clan/fastapi_sqlalchemy_mysql#4]
好像没有APScheduler的用法，我测试了一下出现报错，只有第一次成功：
Run time of job "func (trigger: interval[0:00:03], next run at: 2023-04-04 16:45:25 CST)" was missed by 0:00:03.410931

能不能弄个定时任务示例？（异步好像是用AsyncIOScheduler）

**Comment by wu-clan** [comment]
没问题，预计明天更新

这个错误好像是APScheduler会缓存执行时间，但是fastapi服务被意外关闭，导致未执行scheduler.close()方法

**Comment by wu-clan** [comment]
Hi, @downdawn 

我已经添加了相关代码，但未进行测试

不过，我在另一个实验项目中有完整的使用它，在这里[NinjaXia](https://github.com/wu-clan/NinjaXia)，希望可以帮到你

**Comment by downdawn** [comment]
哈喽，很感谢你及时回复。

我拉取了最新代码并且测试了，发现还有一点问题。

封装的Scheduler类里AsyncIOScheduler应该实例化一次就好了，保留init方法其他不要。
`
# 调度器
scheduler = Scheduler().init
`
然后其他运行的地方正常调用apscheduler原生方法，task_demo四个接口全部正常运行。

最后我还想和你讨论一些其他问题，可能不适合这里，我新开一个issue吧。

谢谢。

**Comment by wu-clan** [comment]
感谢你的反馈。

之所以不使用 `scheduler = Scheduler().init`，这是我有意而为之的

因为对于大多常规项目的开发人员来讲，多数人喜欢二次封装原生方法，比如添加一些日志记录等等

**Comment by downdawn** [comment]
是的，我明白，但是这样就无法正常使用了。

flask可以用g对象存储scheduler实例化对象，然后在需要的地方调用g.scheduler。

fastapi我还不知道有什么好方法。每次init都是新的对象。

**Comment by wu-clan** [comment]
确实如此

我刚刚进行了测试，应该有其他方式，比如存储在接口 request 对象中

但是我不太喜欢使用中间件处理事件

**Comment by wu-clan** [comment]
我想我通过构造方法解决了它

疏忽的，因为我不太常用构造方法和魔术方法

现在它是可用的，也是通用的，请测试

**Comment by downdawn** [comment]
这样确实可行，刚开始我也试过__init__里构造Scheduler对象，但是这样每次调用的时候都会有个烦人的scheduler.init，感觉不够优雅。

如果需要二次封装原生方法，直接继承AsyncIOScheduler类，重写start或者shutdown方法，这样会感觉pythonic一点？

**Comment by wu-clan** [comment]
@downdawn 同意

我喜欢简洁漂亮的东西

或许在自定义方法处添加一点日志记录，它们在 fastapi 启动和关闭是被调用

**Comment by downdawn** [comment]
合理。

但是启动出现loguru错误：
![Uploading image.png…]()

**Comment by wu-clan** [comment]
将日志文件删除，重新启动应该就可以了，loguru 的一个常见错误，但是我没找到很好的解决办法

log 程序需要做一点修改，为了 typing 正常工作，这是必须的，请尝试

```python
from __future__ import annotations

import os

import loguru
from loguru import logger

from backend.app.core import path_conf


class Logger:

    @staticmethod
    def log() -> loguru.Logger:
        # 下面的内容相同
```

**Comment by wu-clan** [comment]
我将删除连接成功的日志记录，只保留错误记录，因为 uvicorn 重载会频繁打印成功消息，这让我看起来难受

![1680767391473](https://user-images.githubusercontent.com/52145145/230310669-0f15da10-a20e-42ef-bbf1-21a5831342b5.png)

**Comment by downdawn** [comment]
哈哈，理解。

代码洁癖是好习惯。
