### ISSUE TITLE
几点讨论与建议

### ISSUE THREAD

**Issue by downdawn** [wu-clan/fastapi_sqlalchemy_mysql#5]
## 讨论一：更清晰的结构建议

现在的api结构是：

api
├── service/
├── v1
│   ├── auth
├──__init__.py
├──casbin.py
├──jwt.py
├──registrar.py
├──routers.py

参考几个开源项目，结合个人建议是api目录下保留最简单的结构，casbin、jwt、registrar可以移动到其他目录，比如core。

api
├── service/
├── v1
│   ├── auth
├──__init__.py

api——>__init__.py
```
from fastapi import APIRouter
from api.auth import router as auth_router

v1 = APIRouter(prefix='/v1')

v1.include_router(auth_router)
```

api——>v1——>auth——>__init__.py
```
from fastapi import APIRouter
from api.auth.user import router as user_router

router = APIRouter(prefix='/auth', tags=['认证'])

router.include_router(user_router, prefix='/user')
```

## 讨论二：基于类的视图

参考该讨论：[https://github.com/zhanymkanov/fastapi-best-practices/issues/4](https://github.com/zhanymkanov/fastapi-best-practices/issues/4)与fastapi-utils项目

基于类的比每个零散的方法看起来会更加清晰，并且可以在一个py管理多个路由（有时需要）
```
from utils.cvb import cbv

router = APIRouter(prefix='/api')


@cbv(router)
class APIRouter:
    user: User = Depends(get_current_user)
    service = ApiService()

    @router.get('', summary='获取所有API', response_model=Page[GetAllApi])
    async def get_all_api(self):
        print(self.user)
        return await self.service.get_api_list()
```
如上，原先的service文件里的方法也封装成ApiService类。同时建议service应该每个路由模块里都有一个，类似如下结构：

api
├── auth
│   ├── user.py
│   ├── service.py
├──__init__.py

这样的话，应该有个Service基类，包含常见的query、create、update、delete方法。

同时`async with async_db_session.begin() as db:`每个方法都有，可以进一步优化？

## 讨论三：权限

casbin是go项目扩展出来的思想？感觉有点冗重，权限这块自己封装比较好自定义。

简单的基于redis或者mysql定义crud，可以对不同路由或者请求方法设置不同的权限。

目前还没有很好的实现方法，但是参考过往的项目应该不难。

**Comment by wu-clan** [comment]
> 讨论一：更清晰的结构建议

观点：

1. registrar 可以移动到 core 目录，它属于核心的一部分，其他文件不会，它们只属于 api, 而且放在这里是显而易见的
2. router 的配置很多人会在主程序（如 main.py）同级新建文件夹去集中定义，但我觉得那是十分多余的，主路由应保持与 api 同级，至于为什么没放在 \_\_init__, 是因为参照 django urls.py

变动：

1. router 可以更改为使用 \_\_init__ 记录，但是它的内容不会改变，它是为了集中管理 restful 风格
2. 是否要删除 api 子目录定义，全部放在根目录下，由用户自己扩展子路由，因为这个项目只是一个参考目的；我觉得可以在 crud 分支这样做，在 plus 分支或许可以添加子路由示例

**Comment by wu-clan** [comment]
> 讨论二：基于类的视图

观点：

1. 我不确定是否要使用类视图，因为它不是原生的，对单个api的定义会有什么影响吗？我后面会看一下 `fastapi-utils`
2. service 或许可以封装成类，有助于结构梳理，但不应该与api文件放在一起，必须分开
3. `async_db_session.begin()` 现在是自由选择的，目前的实现原理是全部定义在 service 中，如果在 api 需要调用返回值，则在 api 上面定义 db 参数；其实，按理来说应该全部在 api 中定义 db，因为每一个接口都会看起来是完整的，并且是线程安全的，但是那样看起来有点丑，可以通过中间件将 db 携带在 request 对象上，在 fastapi 中完全可行，回过头来，我不喜欢使用中间件处理事件，而且，这样的 api 看起来像 django, flask...

变动：

1. 将 service 方法移动到类
2. 每个 api 都定义 db 参数？

**Comment by wu-clan** [comment]
> 讨论三：权限

观点：

是的，casbin 是 go 的权限核心思想，pycasbin 是扩展而来，它的工作方式还是挺有有意思的，完全可以自己封装定义

变动：

我应该不会添加此功能，就目前而言，我不准备再维护 plus 分支，太多的分支让我有点难堪，如果你愿意，我可以新建一个仓库来做当前仓库的扩展，并且只保留一个分支，我们可以叫它 pro，邀请你成为它的开发维护人员，同样的，你也可以新建一个仓库邀请我，我很乐意接受

**Comment by hsluoyz** [comment]
@wu-clan 感谢提供此demo，作为fastapi + pycasbin的演示！我们可以把这个仓库加到casbin官网上，作为一个fastapi集成casbin的指南教程。同时建议增加英文版README，这样可以扩大国际受众。

@downdawn PyCasbin是由Casbin社区官方支持的Python版本。由于需要支持各种场景，因此功能会较为丰富。具体到某个项目中，建议如题中所说，可以做个wrapper先封装出一套函数再进行使用。既可以满足定制化使用，又可以享受到pycasbin所支持的各种强大功能，如各类数据库对接等。比完全自己home-made一个会方便和安全很多。毕竟是究竟各类公司、场合考验的成熟项目，有漏洞也早被修复的差不多了；而完全靠自己写，则很容易写出安全漏洞来。

**Comment by wu-clan** [comment]
@hsluoyz 感谢关注，为此我感到非常荣幸，casbin 的确很好，我一眼认出了你的头像😃

**Comment by downdawn** [comment]
@wu-clan 我找了很多fastapi的项目，发现这个项目比较贴合实际（可能是对我而言）。同时最近打算在新项目使用fastapi（未来趋势），因此有在研究一些具体的实现。fastapi_sqlalchemy_mysql目前有很多分支管理起来会有点麻烦，我支持你新建一个仓库并且很乐意能够提供一点帮助。

@hsluoyz Casbin是一个很棒的项目。你说的有道理，开源项目经过实践的会更加安全，之前我只是粗略的看了几遍文档，有时间我会深入阅读源码，这样自定义起来应该会更加得心应手。

**Comment by downdawn** [comment]
> > 讨论一：更清晰的结构建议
> 
> 观点：
> 
> 1. registrar 可以移动到 core 目录，它属于核心的一部分，其他文件不会，它们只属于 api, 而且放在这里是显而易见的
> 2. router 的配置很多人会在主程序（如 main.py）同级新建文件夹去集中定义，但我觉得那是十分多余的，主路由应保持与 api 同级，至于为什么没放在 __init__, 是因为参照 django urls.py
> 
> 变动：
> 
> 1. router 可以更改为使用 __init__ 记录，但是它的内容不会改变，它是为了集中管理 restful 风格
> 2. 是否要删除 api 子目录定义，全部放在根目录下，由用户自己扩展子路由，因为这个项目只是一个参考目的；我觉得可以在 crud 分支这样做，在 plus 分支或许可以添加子路由示例

同意你的想法。我的主要观点是让项目结构看起来简洁明了，太多目录可能会造成干扰，因为实际写业务代码的时候就在几个目录里切换。一些不经常变动的可以整合在一起，比如enums可以移动到common。当然一些必要还是要保留。

**Comment by downdawn** [comment]
> 

1、我们可以把fastapi-utils的cvb方法单独拿出来使用，可能放到utils？
2、service封装成类可以做一些有意思的扩展，比如继承一个自定义的ServiceBase，包含一些基础方法或者抽象类。async_db_session.begin()每个方法都有是不是可以提取成闭包函数？或者这里可以用DependsSession？

现在的业务流程大概是：model-schema-curd-service-router。curd和service算是对router业务的提炼。

**Comment by downdawn** [comment]
> > 讨论三：权限
> 
> 观点：
> 
> 是的，casbin 是 go 的权限核心思想，pycasbin 是扩展而来，它的工作方式还是挺有有意思的； 当然，完全可以自己封装定义权限
> 
> 变动：
> 
> 我应该不会添加此功能（自定义权限），就目前而言，我不太想再维护 plus 分支，太多的分支让我有点难堪，如果你愿意，我可以新建一个仓库来做当前仓库的扩展，并且只保留一个分支，我们可以叫它 pro，邀请你成为它的开发维护人员，同样的，你也可以新建一个仓库邀请我，我很乐意接受

在get_casbin_enforcer方法里我看到"由于 casbin_sqlalchemy_adapter 内部使用的 SQLAlchemy 同步, 这里只能使用: mysql+pymysql"，这里有更好的解决方法吗？权限我更喜欢放在redis里，因为每次都要判断会更快。

**Comment by wu-clan** [comment]
> 同意你的想法。我的主要观点是让项目结构看起来简洁明了，太多目录可能会造成干扰，因为实际写业务代码的时候就在几个目录里切换。一些不经常变动的可以整合在一起，比如enums可以移动到common。当然一些必要还是要保留。

同意，不过在这里，暂时保留它

**Comment by wu-clan** [comment]
> > 
> 
> 1、我们可以把fastapi-utils的cvb方法单独拿出来使用，可能放到utils？ 2、service封装成类可以做一些有意思的扩展，比如继承一个自定义的ServiceBase，包含一些基础方法或者抽象类。async_db_session.begin()每个方法都有是不是可以提取成闭包函数？或者这里可以用DependsSession？
> 
> 现在的业务流程大概是：model-schema-curd-service-router。curd和service算是对router业务的提炼。

1. fastapi-utils问题移动到新仓库，它更适合在那里
2. 对于service闭包和DependsSession可以评论代码demo吗？感兴趣

**Comment by wu-clan** [comment]
> 在get_casbin_enforcer方法里我看到"由于 casbin_sqlalchemy_adapter 内部使用的 SQLAlchemy 同步, 这里只能使用: mysql+pymysql"，这里有更好的解决方法吗？权限我更喜欢放在redis里，因为每次都要判断会更快。

完全有，但是我没有实践过，casbin的存储器是多种多样的，redis存储器肯定是有的；

在那里之所以这样使用是因为官方的 sqlalchemy 异步存储器还未实现，在这里 [pycasbin](https://github.com/pycasbin)

**Comment by downdawn** [comment]
> > > 
> > 
> > 
> > 1、我们可以把fastapi-utils的cvb方法单独拿出来使用，可能放到utils？ 2、service封装成类可以做一些有意思的扩展，比如继承一个自定义的ServiceBase，包含一些基础方法或者抽象类。async_db_session.begin()每个方法都有是不是可以提取成闭包函数？或者这里可以用DependsSession？
> > 现在的业务流程大概是：model-schema-curd-service-router。curd和service算是对router业务的提炼。
> 
> 1. fastapi-utils问题移动到新仓库，它更适合在那里
> 2. 对于service闭包和DependsSession可以评论代码demo吗？感兴趣

大概像这样：
```
from functools import wraps


def db_decorator(func):
    @wraps(func)
    async def wrapper(*args, **kwargs):
        async with async_db_session.begin() as db:
            return await func(db, *args, **kwargs)
    return wrapper


class ApiService:

    @staticmethod
    @db_decorator
    async def get_api_list(db):
        return await paginate(db, ApiDao.get_all_apis())
```

**Comment by wu-clan** [comment]
Amazing!

**Comment by downdawn** [comment]
> > 同意你的想法。我的主要观点是让项目结构看起来简洁明了，太多目录可能会造成干扰，因为实际写业务代码的时候就在几个目录里切换。一些不经常变动的可以整合在一起，比如enums可以移动到common。当然一些必要还是要保留。
> 
> 同意，不过在这里，暂时保留它，（让我们为新仓库起个名字，这让我有点头疼）

![image](https://user-images.githubusercontent.com/41266749/230548934-4d24af71-9a75-45b7-a417-69e7f0768b07.png)

确实头疼，这里FastSecure相对靠谱一点点。

对了，_BaseMixin应该保留基本的id、created_time、updated_time就够用了。create_user和update_user不适用与全部。

**Comment by downdawn** [comment]
> > > 同意你的想法。我的主要观点是让项目结构看起来简洁明了，太多目录可能会造成干扰，因为实际写业务代码的时候就在几个目录里切换。一些不经常变动的可以整合在一起，比如enums可以移动到common。当然一些必要还是要保留。
> > 
> > 
> > 同意，不过在这里，暂时保留它，（让我们为新仓库起个名字，这让我有点头疼）
> 
> ![image](https://user-images.githubusercontent.com/41266749/230548934-4d24af71-9a75-45b7-a417-69e7f0768b07.png)
> 
> 确实头疼，这是chatgpt回答的，FastSecure相对靠谱一点点。
> 
> 对了，_BaseMixin应该保留基本的id、created_time、updated_time就够用了。create_user和update_user不适用与全部。

**Comment by wu-clan** [comment]
@downdawn 我已经创建并邀请了你, 我叫它 [fastapi_best_architecture](https://github.com/wu-clan/fastapi_best_architecture), 我会抽时间把一些问题移动到那里

> 对了，_BaseMixin应该保留基本的id、created_time、updated_time就够用了。create_user和update_user不适用于全部。

我想我会继续保留，现在添加它很容易，并且很好集成，但是当你有大量models时再想去扩展它，会有很大工作量，除非你给出对其很不利的实例

**Comment by downdawn** [comment]
ok。或许可以换个地方讨论了

**Comment by wu-clan** [comment]
> 是否要删除 api 子目录定义，全部放在根目录下，由用户自己扩展子路由，因为这个项目只是一个参考目的；我觉得可以在 crud 分支这样做，在 plus 分支或许可以添加子路由示例

我改变主意了，所有分支的api我都放在了根目录下，对于子目录的子路由来讲，让我有点混乱，我必须添加一个额外的路径名称，我拒绝这样做，所以，我将它交给用户自定义

**Comment by downdawn** [comment]
> > 是否要删除 api 子目录定义，全部放在根目录下，由用户自己扩展子路由，因为这个项目只是一个参考目的；我觉得可以在 crud 分支这样做，在 plus 分支或许可以添加子路由示例
> 
> 我改变主意了，所有分支的api我都放在了根目录下，对于子目录的子路由来讲，让我有点混乱，我必须添加一个额外的路径名称，我拒绝这样做，所以，我将它交给用户自定义

具体是哪里混乱呢？或许可以举例探讨一下

**Comment by wu-clan** [comment]
> ## 讨论一：更清晰的结构建议

<details><summary>Details</summary>
<p>

> 现在的api结构是：
> 
> api
> ├── service/
> ├── v1
> │   ├── auth
> ├──__init__.py
> ├──casbin.py
> ├──jwt.py
> ├──registrar.py
> ├──routers.py
> 
> 参考几个开源项目，结合个人建议是api目录下保留最简单的结构，casbin、jwt、registrar可以移动到其他目录，比如core。
> 
> api
> ├── service/
> ├── v1
> │   ├── auth
> ├──__init__.py
> 
> api——>__init__.py
> ```
> from fastapi import APIRouter
> from api.auth import router as auth_router
> 
> v1 = APIRouter(prefix='/v1')
> 
> v1.include_router(auth_router)
> ```
> 
> api——>v1——>auth——>__init__.py
> ```
> from fastapi import APIRouter
> from api.auth.user import router as user_router
> 
> router = APIRouter(prefix='/auth', tags=['认证'])
> 
> router.include_router(user_router, prefix='/user')
> ```
> 
</p>
</details> 

我保留了 routers.py，没有将它移动到 __init__，在 routers 中，按照我的想法，为了 restful 统一管理，我加入了 `prefix` 和 `tag`，而不是 `v1.include_router(auth_router)` 这样简单的东西，这样以来，在子目录的__init__文件中，像你的例子中一样：
```python
from fastapi import APIRouter
from api.auth.user import router as user_router

router = APIRouter(prefix='/auth', tags=['认证'])

router.include_router(user_router, prefix='/user')
```
我还需要在APIRouter添加一个 `prefix` 和 `tag`，然后，在 `router.include_router(user_router, prefix='/user')` 也必须有 `prefix`，如果没有，我在接口函数就不能使用空字符串的路径参数，像这样：
```python
@api.get('', response_model=Page[GetAllApi], dependencies=[DependsUser])
async def get_all_api():
    return await ApiService.get_api_list()
```
我必须改为：
```python
@api.get('/')
```
这样以来，对于没有额外路径名称的接口来讲，末尾总是以 `/` 结尾，我拒绝这样做；

按照我现在的做法，接口将像这样：

get:
```
/v1/apis
```
post:
```
/v1/apis
```
put:
```
/v1/apis/{id}
```
......

如果更多的子路由，将像这样

get:
```
/v1/apis/api/
```
post:
```
/v1/apis/api/
```
put:
```
/v1/apis/api/{id}
```
......

**Comment by downdawn** [comment]
> 

是的，我也注意到了fastapi对APIRouter的限制，所以当时我调整这个结构也花一点时间。

其实对于在api里实例一个api = APIRouter()，在user里实例一个user = APIRouter()，我都觉得有点别扭。期望可以统一成router = APIRouter()。

其他没有异议，完全同意。

**Comment by wu-clan** [comment]
我会尝试一下全局 router = APIRouter() 
这样 routers 里面将全是 router
我主要考虑参数命名全相同的话，如果接口出错，定位会不会造成干扰，对导入会不会造成什么影响，IDE的智能提示会不会不太友好

**Comment by wu-clan** [comment]
暂时放弃使用全局 router 统一命名

会导致 IDE 包导入智能提示问题
